[book]
authors = ["Jack Sibley"]
language = "en"
multilingual = false
src = "src"
title = "Magic: The Gathering Comprehensive Rules"

[build]
build-dir = "docs"  

[output.html]
site-url = "ancestral.vision"